variables:
- name: working-dir
  value: 'soft_bulk_delete'

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - 'soft_bulk_delete/*'

schedules:
- cron: "0 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23 * * *"
  displayName: Clean-up closed tickets every hour
  branches:
    include:
    - main
  always: true

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: python -m pip install --upgrade pip requests
  displayName: 'Install dependencies'

- task: PythonScript@0
  env:
    Z_USER: $(zendesk.user)
    Z_API_TOKEN: $(zendesk.token)
  inputs:
    scriptSource: 'filePath'
    scriptPath: '$(working-dir)/soft_bulk_delete.py'